# build image

FROM dlanguage/dmd AS build-env

WORKDIR /app

COPY *.d ./

RUN dmd -O -release -inline -boundscheck=off -of=./csv_test ./csv_test.d ./fastcsv.d

# runtime image

FROM ubuntu:16.04

WORKDIR /app

COPY --from=build-env /app/csv_test .

VOLUME ['/data', '/output', '/resources']

CMD /resources/run.sh d_dmd.txt
